# Generated by Django 2.2.4 on 2019-08-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_all',
            name='stock_code',
            field=models.CharField(default=0, max_length=45),
            preserve_default=False,
        ),
    ]
