# Generated by Django 2.2.4 on 2019-08-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_stock_all_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_all',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock_all',
            name='amt_change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock_all',
            name='close',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock_all',
            name='high',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock_all',
            name='low',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock_all',
            name='pct_change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock_all',
            name='pre_close',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock_all',
            name='vol',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
