# Generated by Django 2.2.4 on 2019-08-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190804_1259'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock_all',
            unique_together={('state_dt', 'stock_code')},
        ),
    ]
