# Generated by Django 2.2.4 on 2019-08-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190804_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_all',
            name='state_dt',
            field=models.CharField(max_length=45),
        ),
    ]
