# Generated by Django 2.2.4 on 2019-08-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190808_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_basic3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=45)),
                ('symbol', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('area', models.CharField(max_length=45)),
                ('industry', models.CharField(max_length=45)),
                ('fullname', models.CharField(max_length=45)),
                ('enname', models.CharField(max_length=45)),
                ('market', models.CharField(max_length=45)),
                ('exchange', models.CharField(max_length=45)),
                ('curr_type', models.CharField(max_length=45)),
                ('list_status', models.CharField(max_length=45)),
                ('list_date', models.CharField(max_length=45)),
                ('delist_date', models.CharField(max_length=45)),
                ('is_hs', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'stock_basic3',
            },
        ),
    ]
