# Generated by Django 2.2.4 on 2019-08-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_stock_basic3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_basic3',
            name='delist_date',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
