# Generated by Django 2.2.4 on 2019-08-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190816_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_basic3',
            name='enname',
            field=models.CharField(max_length=145),
        ),
    ]
