# Generated by Django 2.2.4 on 2019-08-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190816_1340'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock_basic3',
            unique_together={('ts_code', 'symbol')},
        ),
    ]
