# Generated by Django 2.2.4 on 2019-08-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190816_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=45)),
                ('trade_date', models.CharField(max_length=45)),
                ('close', models.DecimalField(decimal_places=2, max_digits=20)),
                ('turnover_rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('turnover_rate_f', models.DecimalField(decimal_places=4, max_digits=20)),
                ('volume_ratio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pe', models.DecimalField(decimal_places=4, max_digits=20)),
                ('pe_ttm', models.DecimalField(decimal_places=4, max_digits=20)),
                ('pb', models.DecimalField(decimal_places=4, max_digits=20)),
                ('ps', models.DecimalField(decimal_places=4, max_digits=20)),
                ('ps_ttm', models.DecimalField(decimal_places=4, max_digits=20)),
                ('total_share', models.DecimalField(decimal_places=4, max_digits=20)),
                ('float_share', models.DecimalField(decimal_places=4, max_digits=20)),
                ('free_share', models.DecimalField(decimal_places=4, max_digits=20)),
                ('total_mv', models.DecimalField(decimal_places=4, max_digits=20)),
                ('circ_mv', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
            options={
                'db_table': 'daily_basic',
            },
        ),
    ]
