# Generated by Django 2.2.4 on 2019-08-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_daily_basic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='daily_basic',
            unique_together={('ts_code', 'trade_date')},
        ),
    ]
